### ISSUE TITLE
Compile issue for RP2040 Connect

### ISSUE THREAD

**Issue by ecosky** [khoih-prog/WiFiWebServer#11]
Line 149 of WiFiWebServer.h doesn't work with RP2040 Connect on PlatformIO, fix is simple, just add the !defined as shown below:

// KH, For PROGMEM commands
// ESP32/ESP8266 includes <pgmspace.h> by default, and memccpy_P was already defined there
#if !(ESP32 || ESP8266) && !defined(ARDUINO_NANO_RP2040_CONNECT)
  #include <avr/pgmspace.h>
  #define memccpy_P(dest, src, c, n) memccpy((dest), (src), (c), (n))
#endif

Thanks to maxgerhardt for the fix. More details on this over here, https://community.platformio.org/t/rp2040-connect-wifiwebserver-build-issues/23801/2

**Comment by khoih-prog** [comment]
HI @ecosky 

Can you try again using the new [**WiFiWebServer** releases v1.4.1](https://github.com/khoih-prog/WiFiWebServer/releases/tag/v1.4.1) ? 

It's possible there is some bug or **settings not correct in PIO** because there is **no issue with  Arduino IDE in compiling at all.**

The default `lib_compat_mode = soft` is really bad for multi-platform code, especially for new PIO users. Wrong libraries could be included and creating compile errors.

---

### Releases v1.4.1

1. Change option for PIO `lib_compat_mode` from default `soft` to `strict` to minimize compile error in cross-platform
2. Update `Packages' Patches` for many boards

**Comment by ecosky** [comment]
Thanks for the suggestion. I updated to 1.4.1 and get the same error unless I add the **&& !defined(ARDUINO_NANO_RP2040_CONNECT)**

I'm admittedly new to PlatformIO so could easily be doing something wrong, however this line of code appears to be including the avr/pgmspace.h if some defines are _not_ present, which may be intentional but from what I can tell so far the avr/pgmspace.h I think is part of the [AVR LIBC library](https://www.nongnu.org/avr-libc/) that is not used by the RP2040? I could be wrong there. All I know is that by not including this on the RP2040 connect, it works for me. I started with an empty project and the WebServer example, so I'm not sure where I might have gone wrong to trigger this if it is something I did. 

I added some warnings to test which one of these were triggering the #include, and any of them would trigger that condition. 
```

#if !(ESP32)
#warning MATCHING: ESP32
#endif
#if !(ESP8266)
#warning MATCHING: ESP8266
#endif
#if !(defined(ARDUINO_PORTENTA_H7_M7))
#warning MATCHING: defined(ARDUINO_PORTENTA_H7_M7)
#endif
#if !(defined(ARDUINO_PORTENTA_H7_M4))
#warning MATCHING: defined(ARDUINO_PORTENTA_H7_M4)
#endif

// KH, For PROGMEM commands
// ESP32/ESP8266 includes <pgmspace.h> by default, and memccpy_P was already defined there
#if !(ESP32 || ESP8266 || defined(ARDUINO_PORTENTA_H7_M7) || defined(ARDUINO_PORTENTA_H7_M4)) && !defined(ARDUINO_NANO_RP2040_CONNECT)
  #include <avr/pgmspace.h>
  #define memccpy_P(dest, src, c, n) memccpy((dest), (src), (c), (n))
#endif

```

Here's the output:

`In file included from src\defines.h:372,
                 from src\main.cpp:18:
.pio\libdeps\nanorp2040connect\WiFiWebServer\src/WiFiWebServer.h:149:2: warning: #warning MATCHING: ESP32 [-Wcpp]
  149 | #warning MATCHING: ESP32
      |  ^~~~~~~
.pio\libdeps\nanorp2040connect\WiFiWebServer\src/WiFiWebServer.h:152:2: warning: #warning MATCHING: ESP8266 [-Wcpp]
  152 | #warning MATCHING: ESP8266
      |  ^~~~~~~
.pio\libdeps\nanorp2040connect\WiFiWebServer\src/WiFiWebServer.h:155:2: warning: #warning MATCHING: defined(ARDUINO_PORTENTA_H7_M7) [-Wcpp]
  155 | #warning MATCHING: defined(ARDUINO_PORTENTA_H7_M7)
      |  ^~~~~~~
.pio\libdeps\nanorp2040connect\WiFiWebServer\src/WiFiWebServer.h:158:2: warning: #warning MATCHING: defined(ARDUINO_PORTENTA_H7_M4) [-Wcpp]
  158 | #warning MATCHING: defined(ARDUINO_PORTENTA_H7_M4)
      |  ^~~~~~~`

**Comment by khoih-prog** [comment]
Hi @ecosky 

Thanks for testing and publish the results. I still don't see the compile error in your post

The actual `pgmspace.h` file of mbed_rp2040 core is in the **deprecated** section of the core, for the core is v.2.5.2,

`2.5.2/cores/arduino/api/deprecated-avr-comp/avr/pgmspace.h`

and surely the Arduino IDE doesn't use it and there is no conflict at all.

Somehow, PIO, by using some wrong settings, you have to find out where, and include that **deprecated**  file, therefore, conflict happens.

It's easy to add the **&& !defined(ARDUINO_NANO_RP2040_CONNECT)**, but I'm reluctant to do that kind of kludge, without knowing and fixing the real cause, which can create many more issues in the future.

I suggest you **discuss in PIO forum**, to understand then **fix the real PIO issue** => why it's OK with Arduino IDE, but not with PIO.

Good Luck,

**Comment by khoih-prog** [comment]
Hi,

Just noted that you're still using mbed_rp2040 core v2.4.1. Can you try to update to latest [**ArduinoCore-mbed** core v2.5.2](https://github.com/arduino/ArduinoCore-mbed/releases/tag/2.5.2) to see any better ?

**Comment by khoih-prog** [comment]
Hi @ecosky 

I guess I can see the real issue now

It's possible that PIO, when installing [ArduinoCore-mbed core](https://github.com/arduino/ArduinoCore-mbed), just installs from the GitHub (or something similar to that), and the whole directory **`2.5.2/cores/arduino/api` is missing.**

Could you check if you have that directory **`2.5.2/cores/arduino/api`  in PIO ArduinoCore-mbed  core**?

I guess that directory is added only by Arduino IDE, running some installation script.

Without that, you'll get the compile error such as ??? 

```
defines.h:372:10: fatal error: avr/pgmspace.h: No such file or directory
 #include <avr/pgmspace.h>
```

**Comment by ecosky** [comment]
Yep, that's the exact error I have been getting. I've been trying to figure out how to get ArduinoCore-mbed 2.5.2 installed but it seems to be unavailable to me for some reason, and the update feature isn't aware of it yet.

I don't see that directory - could you please provide a more complete path (with visible slashes)? Perhaps I'm looking in the wrong place. Thanks!

**Comment by khoih-prog** [comment]
Check in your Arduino IDE core directory, such as in Linux

`~/.arduino15/packages/arduino/hardware/mbed_rp2040/2.5.2/cores/arduino/api`

In Windows, something similar to that

It's wrong if you add the core just by doing as suggested in [**PIO Raspberry Pi RP2040**](https://docs.platformio.org/en/latest/platforms/raspberrypi.html)

```
platform = https://github.com/platformio/platform-raspberrypi.git
```

**Comment by khoih-prog** [comment]
Doing that way, you are possibly missing many requested directories and tools

**Comment by khoih-prog** [comment]
PIO is missing this [**package_full.sh#L15-L17**](https://github.com/arduino/ArduinoCore-mbed/blob/master/package_full.sh#L15-L17)

```
# Clone ArduinoCore-api in parent folder and create symlinks
git clone git@github.com:arduino/ArduinoCore-API.git ../api/
ln -s ../../../api/api cores/arduino/api
```

That script must be used / run to install the core correctly

**Comment by khoih-prog** [comment]
You have to post an issue in PIO to fix once-and-for-all, because who knows this can happen to any other cores?

**Comment by khoih-prog** [comment]
Using v2.4.2 is still OK as we already know the culprit. Don't need to wait for v2.5.2.

The issue will happen to all core and/or versions of [ArduinoCore-mbed core](https://github.com/arduino/ArduinoCore-mbed), such as **mbed_nano, mbed_portanta, mbed_rp2040**

**Comment by ecosky** [comment]
On Windows here, and down in C:\Users\accountName\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano I only have a 2.4.1 folder. 

I see when I look at the boards manager in the Arduino IDE there is an update to 2.5.2. Updating it there didn't fix the PIO build, it still finds v2.4.2. I haven't run the Arduino IDE in a while so I'm not surprised it's stale there. I suspect it's not even relevant to this discussion?

Unfortunately, Windows doesn't support the symlink but I can shuffle things around. Can you please share the full path I need to be in when running the above script? Thanks

I see when I look at the boards manager in the Arduino IDE there is an update to 2.5.2. Updating it there didn't fix the PIO build, it still finds v2.4.2.

**Comment by khoih-prog** [comment]
PIO packages is at different location from Arduino IDE.

You just locate your **mbed_rp2040** core, then copy the whole core directory to PIO core directory

`C:\Users\accountName\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\2.4.1\cores\arduino\api`

Just find where is the PIO platforms directory, then copy to overwrite all or just copy the `api` directory only

**Comment by khoih-prog** [comment]
Just check my Windows machine and the `api` is there (I don't know which script the Atrduino IDE uses to install the [**ArduinoCore-API**](https://github.com/arduino/ArduinoCore-API), will find later as I don't use Windows at all, just in some other place to check when necessary)

`C:\Users\accountName\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\2.5.2\cores\arduino\api`

**Comment by khoih-prog** [comment]
That's why you have to follow the instructions in [**ArduinoCore-mbed Installation**](https://github.com/khoih-prog/ArduinoCore-mbed/tree/master#installation)

---

## Installation

### Clone the repository in `$sketchbook/hardware/arduino-git`

```bash
mkdir -p $sketchbook/hardware/arduino-git
cd $sketchbook/hardware/arduino-git
git clone git@github.com:arduino/ArduinoCore-mbed mbed
```

### Clone https://github.com/arduino/ArduinoCore-API into a directory of your choice.

```bash
git clone git@github.com:arduino/ArduinoCore-API
```

### Update the `api` symlink

Create a symlink to `ArduinoCore-API/api` in `$sketchbook/hardware/arduino/mbed/cores/arduino`.

**Comment by maxgerhardt** [comment]
>Could you check if you have that directory 2.5.2/cores/arduino/api in PIO ArduinoCore-mbed core?

The `cores/arduino/api` folder exists in the PlatformIO package. `framework-arduino-mbed` of version 2.4.0 is used [in platform-rasperrypi](https://github.com/platformio/platform-raspberrypi/blob/76011726a908c35a598109b127f3a1a638d7885a/platform.json#L34-L39). PlatformIO has got a proper copy of the 2.4.0 version of the core.

![grafik](https://user-images.githubusercontent.com/26485477/137017103-0b9e2747-0a04-4ac1-af0a-1273f691118b.png)

If the probklem is that the library needs ArduinoCore-mbed version 2.5.2, that's a problem that has to be solved in platform-raspberrypi. The latest version [in the package repo](https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduino-mbed) is 2.4.1. I've opened issue https://github.com/platformio/platform-raspberrypi/issues/19 regarding this.

**Comment by khoih-prog** [comment]
@maxgerhardt 

Thanks, I still wonder why @ecosky doesn't have `api` directory when he's using `mbed_rp2040 core v2.4.1`
Is it possible some more installation steps necessary to follow to get the [Complete **framework-arduino-mbed-2.4.1.tar.gz**](https://dl.registry.platformio.org/download/platformio/tool/framework-arduino-mbed/2.4.1/framework-arduino-mbed-2.4.1.tar.gz), with included `api`

**Comment by maxgerhardt** [comment]
>to get the Complete framework-arduino-mbed-2.4.1.tar.gz, with included api

The file you linked to literally has the `api` folder.

![grafik](https://user-images.githubusercontent.com/26485477/137020676-0937f304-3c16-4cd7-bd0a-707355077b5d.png)

**Comment by maxgerhardt** [comment]
When he said 

>I don't see that directory - could you please provide a more complete path? Perhaps I'm looking in the wrong place. Thanks!

He was probably looking for the Arduino IDE path, not the PlatformIO path `C:\Users\<user>\.platformio\packages\framework-arduino-mbed\cores\arduino\api`. The folder should be there.

**Comment by maxgerhardt** [comment]
Yes he can still get that compile error while having that file. I have that file too

![grafik](https://user-images.githubusercontent.com/26485477/137021684-f31943db-d6f4-428b-890e-d26d5039c85d.png)

but since the PlatformIO Arduino-mbed builder script does not add the folder to the include path in 

https://github.com/platformio/builder-framework-arduino-core-mbed/blob/ceb4f608f9b4834ac4fa5472e1db2a2c2f9d216e/arduino-core-mbed.py#L96-L100

the include error is presented.

I opened https://github.com/platformio/builder-framework-arduino-core-mbed/pull/1 to have that fixed.
