### ISSUE TITLE
 fatal error: functional-vlpp.h: No such file or directory

### ISSUE THREAD

**Issue by pedrogagu** [khoih-prog/WiFiWebServer#12]
In file included from D:\PROYECTOS_ARDUINO\esp8266_led2\esp8266_led2.ino:4:0:
D:\PROYECTOS_ARDUINO\libraries\WiFiWebServer-1.4.2\src/WiFiWebServer.h:122:10: fatal error: functional-vlpp.h: No such file or directory
 #include <functional-vlpp.h>

**Comment by khoih-prog** [comment]
Thanks for using the library.

I suggest that before using any library, you'd better to scan through [**README**](https://github.com/khoih-prog/WiFiWebServer/blob/master/README.md), especially [**Prerequisites**](https://github.com/khoih-prog/WiFiWebServer#prerequisites), if any. Then you'll know you have to install [**functional-vlpp** library](https://github.com/khoih-prog/functional-vlpp) and avoid the error.

Good Luck,
