### ISSUE TITLE
error WIFI_USING_ESP_AT is not supported for AdvancedWebServer

### ISSUE THREAD

**Issue by Jonnx** [khoih-prog/WiFiWebServer#16]
### Describe the bug

I am attempting to run the SimpleWebSocket example on an Arduino Uno Wifi Rev2 as a stepping stone to connect to leverage pusher websockets. When compiling the code to the board i get the error message below.
It may just be that my board is not compatible, but i figured i would ask.

### Steps to Reproduce

1. connect arduino
2. choose board: Arduino Mega AVR -> Arduino Uno WiFi Rev2
2. load "SimpleWebSockets" example
3. click verify / upload

### Expected behavior

code compiles and then attempts to connect to socket server

### Actual behavior

code compiles with error above

### Debug and AT-command log (if applicable)

```
In file included from /var/folders/h1/tt2m6t8j3k30wvy6w3hwdzb40000gn/T/arduino_modified_sketch_773187/SimpleWebSocket.ino:24:0:
defines.h:90:4: error: #error WIFI_USING_ESP_AT is not supported for AdvancedWebServer
   #error WIFI_USING_ESP_AT is not supported for AdvancedWebServer
    ^~~~~
In file included from /var/folders/h1/tt2m6t8j3k30wvy6w3hwdzb40000gn/T/arduino_modified_sketch_773187/defines.h:373:0,
                 from /var/folders/h1/tt2m6t8j3k30wvy6w3hwdzb40000gn/T/arduino_modified_sketch_773187/SimpleWebSocket.ino:24:
/Users/jonasweigert/Documents/Arduino/libraries/WiFiWebServer/src/WiFiWebServer.h:239:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
exit status 1
#error WIFI_USING_ESP_AT is not supported for AdvancedWebServer
```

### Information

Please ensure to specify the following:

Arduino IDE version: 1.18.19
WifiNINA 1.8.3
OS: Mac OSX
```

**Comment by khoih-prog** [comment]
Hi @Jonnx 

Thanks for your interest in the library, which is currently is not supporting megaAVR boards, such as UNO WiFi Rev2 using WiFi101.

I'll release a new library version by tomorrow to support megaAVR architecture.

Cheers,

**Comment by khoih-prog** [comment]
Hi @Jonnx 


The new [**WiFiWebServer releases v1.6.2**](https://github.com/khoih-prog/WiFiWebServer/releases/tag/v1.6.2) has just been published.

Even `UNO_WIFI_REV2` is supported now, the megaAVR family is outdated and with limited memory. It's advisable to move to new type of more powerful boards, such as `Nano_RP2040_Connect`, ESP32, etc. to avoid problem in the very near future.

Best Regards,

---

### Releases v1.6.2

1. Add support to megaAVR boards (UNO_WIFI_REV2, NANO_EVERY) using [Arduino megaAVR core](https://github.com/arduino/ArduinoCore-megaavr)
2. Update `Packages' Patches`
