### ISSUE TITLE
Integration with Arduino IDE 2.0 doesn't seem to work?

### ISSUE THREAD

**Issue by sanford** [khoih-prog/WiFiWebServer#21]
Installing the WiFiWebServer library in IDE 2.0 works. 

However, trying to include the main header file doesn't appear to work:

#include <WiFiWebServer.h>

returns an error:

Compilation error: WifiWebServer.h: No such file or directory

**Comment by khoih-prog** [comment]
I suggest you use the stabler and proven IDE `v1.8.19` instead of `v2.0.0`

There are still many more bugs there, for experimenting only.

It seems that you or IDE forgot to install the library [**WiFiWebServer**](https://github.com/khoih-prog/WiFiWebServer)
