### ISSUE TITLE
server.send buffer size limited to 4k

### ISSUE THREAD

**Issue by jlemieux55** [khoih-prog/WiFiWebServer#23]
html file or message is > 4500 bytes
server.send  buffer truncates at > 4096
String message="";
message+=("html content is over 4500 bytes");
server.send(200, "text/html", message);

**Comment by jlemieux55** [comment]
forgot to say:
Platform: Arduino MKR1010 (wifinina)

**Comment by khoih-prog** [comment]
HI @jlemieux55 

Actually, the limitation is not the bug of this library, but the limitation of [**WiFiNINA** library](https://github.com/arduino-libraries/WiFiNINA) and certainly modified [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic), prevent this library to send in chunks to deal with large html.

The issue affects all **WiFiNINA**-based boards, such as `Nano_33_IoT`, `Nano_RP2040_Connect`, `MKR1010`, etc. usng this library or not.

You can test and verify by using other boards, such as ESP32/ESP8266, Portenta_H7, RP2040W and see sending html contents much larger than `4K` is OK

You can post an issue on WiFiNINA to help fix thus issue / enhance.

I don't know if I have time to check and fix the  [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic).

Try to switch to better, even cheaper boards, such as RP2040W, ESP32/ESP8266, etc.

**Comment by khoih-prog** [comment]
Hi @jlemieux55 

Good news. I just fix the limitation of [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic) and **you now can send very large HTML size**.

Will post the new [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic)  and let you know to try after some some abusive tests.

Be patient.

**Comment by khoih-prog** [comment]
Hi @jlemieux55 

Please check the new release [**WiFiNINA_Generic** v1.8.15-0](https://github.com/khoih-prog/WiFiNINA_Generic/releases/tag/v1.8.15-0) which permitssending much larger data than total 4K.

Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiNINA_Generic#contributions-and-thanks)

---

### Releases v1.8.15-0

1. Fix severe limitation to permit sending much larger data than total 4K. Check [server.send buffer size limited to 4k #23](https://github.com/khoih-prog/WiFiWebServer/issues/23)
2. Add examples [WiFiWebServer_BigData](https://github.com/khoih-prog/WiFiNINA_Generic/tree/master/examples/WiFiWebServer_BigData) to demo how to send much larger data than total 4K
3. Optimize code
4. Clean up
