### ISSUE TITLE
WifiWebServer and EthernetWebServer Incompatible

### ISSUE THREAD

**Issue by samtd** [khoih-prog/WiFiWebServer#4]
Hey. You have great libraries. Congratulations.
I'm trying use both libraries WifiWebServer and EthernetWebServer in my project and have redefinition problems.
With only one library i don't have any problem. 

Examples:
error: multiple definition of 'enum mime::type' enum type 
error: redefinition of 'struct mime::Entry' struct Entry
error: multiple definition of 'enum HTTPMethod' enum HTTPMethod

**Comment by khoih-prog** [comment]
Thanks for using the libraries and your encouraging words.

This is expected as users seldom uses both libraries together.

You can **easily rewrite/merge** those 2 libraries together, just remove the duplicating files / declarations. Just be careful that there could be resource conflicts, memory issue, etc. What board / Etjernet / WiFi are you using ?

I'm sorry I don't have time to do this just to be used only for very rare use cases and close the issue now, unless there are many more similar requests.
