### ISSUE TITLE
Sending a large HTML 

### ISSUE THREAD

**Issue by SimeonNewRiser** [khoih-prog/WiFiWebServer#8]
Hello, 

is it possible to send a large HTML response using the library that you have created? If so, could you please provide a code snippet of how to achieve it? Thanks so much for the work you put into this library :)

**Comment by khoih-prog** [comment]
It's not easy to send a large HTML files. This is the MCU world, with limited resources, many things we can't do easily, or even impossible to do.

You also have first try with the WiFi library you're using to know the limitations (buffer limitation, etc. )

Check these similar issues

1. [**Problem with page larger than 2k**](https://github.com/khoih-prog/EthernetWebServer/issues/7)
2. [**EthernetWebServer does not read and send html.h file to web browser**](https://github.com/khoih-prog/EthernetWebServer/issues/6)

and Google, ask on the forums for guidance.

I'm afraid I can't help anything here.

Good Luck,
